# Lec 2 (data types)

Mutable(List,Dictionary,Sets) and Immutable(Tuples)

In [ ]:

#Lists
l1=[2,3,'4',5]
l1.append(6)
l1.remove('4')
print(l1)
print(l1[2])

5


In [ ]:
#Dictionaries
#Like hashMap 1 key can have only 1 value
d1={"one":1,"two":2}
print(d1)
d2={"Yash":{"age":19,"Hometown":"Mumbai"},"Rushank":{"age":19,"Hometown":"Virar"}} #dict of dict
d2["Dhriti"]={"age":20,"Hometown":"Thane"}
print(d2)

{'one': 1, 'two': 2}
{'Yash': {'age': 19, 'Hometown': 'Mumbai'}, 'Rushank': {'age': 19, 'Hometown': 'Virar'}, 'Dhriti': {'age': 20, 'Hometown': 'Thane'}}


In [ ]:
#Sets just like set unique elements
s1={1,2,3,1}
s2=set([1,2,3,4,5,6,3])
print(s1,"and",s2,"union is",s1.union(s2),"and Intersection is",s1.intersection(s2))
# | for union and & for intersection


{1, 2, 3} and {1, 2, 3, 4, 5, 6} union is {1, 2, 3, 4, 5, 6} and Intersection is {1, 2, 3}


In [ ]:
#Tuples (Unique element which cant be changed once made)
t1=(1,2,3,5)
#t1(2)=4 #File "<ipython-input-17-dbcf8ea36cfc>", line 3 Error
print(t1)
#Tuples can be used as directory keys
work={("Rebecca",1):12,("Alex",2):9}
print(work[("Rebecca",1)])

(1, 2, 3, 5)
12


##NumPy: Numerical Python

In [ ]:
import numpy as np
import random
arr=np.array([1,2,3,4,5])
print(arr)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
# ndmin minimum dimension of np array
arr3=np.array([1,3,5,7,9,11],ndmin=3)
print(arr3)
random_array = np.random.rand(3, 3)
print(random_array)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  3  5  7  9 11]]]
[[0.41495974 0.04600886 0.59611285]
 [0.129781   0.63810714 0.28779567]
 [0.82675093 0.78008617 0.2287549 ]]
3.3802012998253907


## Exercise

In [ ]:
# random choice
import random
print(random.choice(l1))

#count till tuple
l2=[1,3,5,(7,8),9,11]
count = 0
for ele in l2:
  if isinstance(ele,tuple):
    break
  count+=1
print(count)

#Dictionary of 5 countries with currency
countries_currencies = {
    "United States": "US Dollar",
    "United Kingdom": "British Pound",
    "Japan": "Japanese Yen",
    "China": "Chinese Yuan",
    "Canada": "Canadian Dollar"
}
print(countries_currencies)

#Reverse tuple list
tp=tuple([1,3,4,5,8,10,13])
tp_list=list(tp)
tp_list.reverse()
tp=tuple(tp_list)
print(tp)

2
3
{'United States': 'US Dollar', 'United Kingdom': 'British Pound', 'Japan': 'Japanese Yen', 'China': 'Chinese Yuan', 'Canada': 'Canadian Dollar'}
(13, 10, 8, 5, 4, 3, 1)


In [ ]:
import numpy as np
#create array with all 1
arr = np.ones(shape=(2,7))
print(arr)
#check if exists
# Define the numpy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the row to search for
target_row = np.array([4, 5, 6])

# sum of all vals
sum=np.sum(array)
print(sum)
# Check if the target row exists in the array
result = np.any(np.all(array == target_row,axis=1))
# Print the result
print(f"Does the array contain the target row? {result}")



[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
45
Does the array contain the target row? True


In [ ]:
import numpy as np

# Define the matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Add the matrices
sum_matrix = np.add(matrix_a, matrix_b)

# Multiply the matrices
product_matrix = np.dot(matrix_a, matrix_b)

# Print the results
print("Sum of matrices:")
print(sum_matrix)
print("\nProduct of matrices:")
print(product_matrix)
flat_mat=product_matrix.flatten()
print(flat_mat)
sor_mat=np.sort(flat_mat)[::-1]
print(sor_mat)
print(np.sort(sum_matrix,axis=1)[::-1])

Stats

In [ ]:
import numpy as np
from scipy import stats

# Define the array
data = np.array([11, 15, 13, 11, 14, 13, 15, 12, 14, 13,
                 15, 12, 11, 14, 13, 12, 11, 15, 14, 13])

# Find the most frequent value and its count
mode_value, mode_count = stats.mode(data)

# Print the most frequent value and its frequency
print(f"Most frequent value: {mode_value}")
print(f"Frequency count: {mode_count}")

# Calculate the mean, variance, and standard deviation
mean = np.mean(data)
variance = np.round(np.var(data),3)
standard_deviation = np.round(np.std(data),3)

# Print the results
print(f"Mean: {mean}")
print(f"Variance: {variance}")
print(f"Standard deviation: {standard_deviation}")

Most frequent value: 13
Frequency count: 5
Mean: 13.05
Variance: 1.947
Standard deviation: 1.396


# Lec 3 (Conditional statements)

In [ ]:
x1=int(input("Enter x1\n"))
x2=int(input("Enter x2\n"))
y1=int(input("Enter y1\n"))
y2=int(input("Enter y2\n"))

ans=(y2-y1)/(x2-x1)
if(x2-x1==0):
  print("vertical Line")
elif(ans>0):
  print("Positive slope")
elif(ans<0):
  print("negative slope")
else:
  print("Horizontal line")


Enter x1
13
Enter x2
4
Enter y1
14
Enter y2
14
Horizontal line


In [ ]:
# Initialize the starting temperature in Celsius
celsius = 10

# Print the header
print("Celsius\tFahrenheit")

# Use a while loop to iterate from 10 to 20 degrees Celsius
while celsius <= 20:
    # Convert Celsius to Fahrenheit using the formula
    fahrenheit = (celsius * 9/5) + 32

    # Print the temperature values
    print(f"{celsius}\t\t{fahrenheit}")

    # Increase the Celsius temperature by 1 degree
    celsius += 1

Celsius	Fahrenheit
10		50.0
11		51.8
12		53.6
13		55.4
14		57.2
15		59.0
16		60.8
17		62.6
18		64.4
19		66.2
20		68.0


In [ ]:
# Create a list of integers
numbers = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 10]

# Create a dictionary to store the frequency of each integer
frequency_dict = {}

# Iterate through the list and count the frequency of each integer
for num in numbers:
    if num not in frequency_dict:
        frequency_dict[num] = 1
    else:
        frequency_dict[num] += 1

# Print the frequency of each integer
for num, freq in frequency_dict.items():
    print(f"Number: {num}, Frequency: {freq}")

Number: 1, Frequency: 2
Number: 2, Frequency: 3
Number: 3, Frequency: 4
Number: 4, Frequency: 4
Number: 5, Frequency: 4
Number: 6, Frequency: 2
Number: 7, Frequency: 2
Number: 8, Frequency: 2
Number: 9, Frequency: 2
Number: 10, Frequency: 1


In [ ]:
def is_prime(n):

  if n <= 1:
    return False

  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False

  return True

print(is_prime(23))

True


In [ ]:
def fact(n):
  ans=1
  while(n>0):
    ans*=n
    n=n-1
  return ans

def rec_fact(n,ans):
  if(n<1):
    return ans
  ans=ans*n*rec_fact(n-1,ans)
  return ans

print(fact(7))
print(rec_fact(7,1))

5040
5040


In [ ]:
greater = lambda x, y: x if x > y else y

x=int(input("Enter x "))
y=int(input("Enter y "))

print(greater(x,y))



Enter x 14
Enter y 34
34


In [ ]:
def elementwise_addition(list1, list2):
  result = map(lambda x, y: x + y, list1, list2)
  return list(result)
# Example usage
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

result = elementwise_addition(list1, list2)

print(result)
from functools import reduce
def odd_sqr(list2):
  odd_no = list((filter(lambda x:x%2 == 1,list2)))
  odd_sqr= list(map(lambda x:x**2,odd_no))
  odd_sum= reduce(lambda x,y:x+y,odd_sqr)
  return odd_sum

print(odd_sqr(list2))

[7, 9, 11, 13, 15]
130
